#!/bin/bash

options="Shutdown\nReboot\nSuspend\nLogout"

choice=$(echo -e "$options" | fuzzel --dmenu)

case "$choice" in
"Shutdown")
	systemctl poweroff
	;;
"Reboot")
	systemctl reboot
	;;
"Suspend")
	"$HOME/Scripts/lock-session" suspend
	;;
"Logout")
	swaymsg exit
	;;
esac
