# Docked before laptop-only so connecting HDMI selects the dock layout.
profile laptop-left {
    output eDP-1 enable mode 1366x768@60.003Hz position 0,0
    output HDMI-A-1 enable mode 1920x1080@60Hz position 1366,0
}
profile monitor-top {
    output eDP-1 enable mode 1366x768@60.003Hz position 0,1080
    output HDMI-A-1 enable mode 1920x1080@60Hz position 0,0
}
profile monitor-right {
    output HDMI-A-1 enable mode 1920x1080@60Hz position 0,0
    output eDP-1 enable mode 1366x768@60.003Hz position 1920,0
}
profile monitor-only {
    output eDP-1 disable
    output HDMI-A-1 enable mode 1920x1080@60Hz position 0,0
}
profile laptop-only {
    output eDP-1 enable mode 1366x768@60.003Hz position 0,0
}
